# Generated by Django 5.0.2 on 2024-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comentPost',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comentUser',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='PostCategory',
            new_name='postCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
